version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ComputerAccessories
      POSTGRES_PASSWORD: Root@123
      POSTGRES_DB: ComputerAccessories 
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"