version: '3.8'

services:
  backend:
    build:
      context: .  # Path to your project directory
      dockerfile: Dockerfile  # Name of the Dockerfile
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ComputerAccessories
      SPRING_DATASOURCE_USERNAME: ComputerAccessories
      SPRING_DATASOURCE_PASSWORD: root@123

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ComputerAccessories
      POSTGRES_USER: ComputerAccessories
      POSTGRES_PASSWORD: root@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: